### ISSUE TITLE
[DSNP] add lastUpdate field in private graph chunk

### ISSUE THREAD

**Issue by aramikm** [LibertyDSNP/schemas#27]
Problem
=======
We will need to know when was the last time that all Prids inside a page got refreshed. This will allow us to determine which pages need to be updated by refreshing their PRId. This is important to ensure that an un-delegated provider would not be able to check Friendship status for a long period of time.

## Acceptence Criterea
- add a new field of type `long` to store the `lastUpdate` timestamp in epoch days for private graph chunk
- add tests

**Comment by JoeCap08055** [comment]
Probably, we only need to store `int` rather than `long`... that allows us to store number of days up to the year 2136

**Comment by aramikm** [comment]
Not required anymore due to conversations.
