### ISSUE TITLE
Document schema IDs for dsnp/instant-seal-node-with-deployed-schemas

### ISSUE THREAD

**Issue by JoeCap08055** [LibertyDSNP/schemas#44]
The Docker image [dsnp/instant-seal-node-with-deployed-schemas](https://hub.docker.com/r/dsnp/instant-seal-node-with-deployed-schemas) should also publish an Overview to DockerHub with some minimal descriptive documentation, including the schema IDs in the contained image.

Currently, as of v1.8.1, the schema IDs match `mainnet` (as documented [here](https://spec.dsnp.org/Frequency/Overview.html#dsnp-over-frequency-schemas)), but that is not always guaranteed to be the case going forward.

**Comment by wesbiggs** [comment]
I added machinery to return the schema mappings as the output from `cli/deploy.ts::deploy()`.

It looks like this (prettified):
```
[
  {
    "schemaName": "tombstone",
    "id": 1
  },
  {
    "schemaName": "broadcast",
    "id": 2
  },
  {
    "schemaName": "reply",
    "id": 3
  },
  {
    "schemaName": "reaction",
    "id": 4
  },
  {
    "schemaName": "profile",
    "id": 5
  },
  {
    "schemaName": "update",
    "id": 6
  },
  {
    "schemaName": "publicKey_keyAgreement",
    "id": 7
  },
  {
    "schemaName": "userPublicFollows",
    "id": 8
  },
  {
    "schemaName": "userPrivateFollows",
    "id": 9
  },
  {
    "schemaName": "userPrivateConnections",
    "id": 10
  },
  {
    "schemaName": "publicKey_assertionMethod",
    "id": 11
  }
]
```

Naively, we could make `npm run deploy` write this to a file or do a template transform; would that be sufficient for the docker image? Is there a specific filename it looks for?

**Comment by JoeCap08055** [comment]
> I added machinery to return the schema mappings as the output from `cli/deploy.ts::deploy()`.
> 
> It looks like this (prettified):
> 
> ```
> [
>   {
>     "schemaName": "tombstone",
>     "id": 1
>   },
> <...>
> ]
> ```
> 
> Naively, we could make `npm run deploy` write this to a file or do a template transform; would that be sufficient for the docker image? Is there a specific filename it looks for?

Unfortunately, this isn't what I was driving at, and I don't really see a way to achieve what I wanted: the description of an image hosted on Docker Hub is controlled by the `LABEL description = ...` tag inside the `Dockerfile` itself.

Having a file inside the image with the deployed schema IDs is probably fine for now, though, especially if we're close to a solution for schema names, which would eliminate the need for publishing known schema IDs.

**Comment by wesbiggs** [comment]
With proposed changes in #46 you should be able to get deterministic answers from `dsnp.getSchemaId()` (or treat the code for the `"default"` schema mapping as documentation for `instant-seal-node`). But let me know if you think more is needed.
